name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        npm ci
    
    - name: Run linting
      run: |
        echo "Running ESLint with CI configuration..."
        npm install -D @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-config-prettier
        npx eslint --config .github/eslint-ci.config.js "{src,apps,libs,test}/**/*.ts" --max-warnings 0
    
    - name: Run tests
      run: npm run test
      
    - name: Build
      run: npm run build 